version: "3"
services:
  app:
    image: artomiris/devops-for-programmers-project-74:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  caddy:
    image: caddy:2.6
    restart: always
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app