FROM node:20.12.2

WORKDIR /app

# Важно для кеширования слоев
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci
RUN npm install -g sequelize-cli

COPY app/. .
RUN make prepare-env

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start